### ISSUE TITLE
Na and K in ExoMolOP database

### ISSUE THREAD

**Issue by AaronDavidSchneider** [ExoMol/exomol.com#12]
Hi,

I know that Na and K are technically not molecules, but atoms. However, it is mentioned in [Chubb et al. 2021](https://ui.adsabs.harvard.edu/abs/2021A&A...646A..21C) that those opacities are computed and accessible on the ExoMolOP database. Its not possible to find them using the web interface, and they are also not part of the [master definition file](www.exomol.com/exomol.all). Tagging @katychubb here.

Thanks for your work on this very useful database!

Cheers
Aaron

**Comment by Trovemaster** [comment]
We will look into it!

**Comment by Trovemaster** [comment]
See new ExoMolOP opacities of K and Na on ExoMol: 
https://exomol.com/data/molecules/K/
https://exomol.com/data/molecules/Na/

**Comment by Trovemaster** [comment]
Thanks @katychubb

**Comment by AaronDavidSchneider** [comment]
Thanks!
