### ISSUE TITLE
Dataset without partition function returned by pf-specific request

### ISSUE THREAD

**Issue by ajwheeler** [ExoMol/exomol.com#14]
If I GET `https://exomol.com/api/?molecule=CO2&datatype=partitionfunction&isotopologues=(17O)(12C)(18O)`, I receive

```
{"(17O)(12C)(18O)": {
    "molecule": "CO2", 
    "mass /u": 46.9982913694, 
    "partitionfunction": {
        "data type": "partition function", 
        "Zak": {
            "description": "A room temperature line list for CO<sub>2</sub> in the HITRAN format calculated using the AMES potential energy surface and an accurate ab initio dipole moment surface.", 
            "recommended": true, 
            "files": [{
                 "url": "exomol.com/db//CO2/17O-12C-18O/Zak/17O-12C-18O__Zak.par", 
                 "description": "A room temperature line list for (17O)(12C)(18O) in the HITRAN format."}]}}}}
```

This dataset appears to not have a `.pf` file.  Is it expected to be returned for this request?

**Comment by Trovemaster** [comment]
The .par datasets do not have partition funcitons, which is why the error. This is type of data is an exception as it is not in the exomol format.

**Comment by ajwheeler** [comment]
Is this dataset intended to show up even when `datatype=partitionfunction` is in the URL?

**Comment by Trovemaster** [comment]
No, not really. Do you think it would be useful?

**Comment by Trovemaster** [comment]
We should probably change the data type of .par from "line list" to something else.

**Comment by ajwheeler** [comment]
The problem isn't that I was expecting the ".par" dataset to show up when I did a query with `datatype=partitionfunction`.  It's the opposite: that it *was* returned, even though it doesn't contain partition function data.

(Apologies if I am misunderstanding.)

**Comment by Trovemaster** [comment]
Ah, I see. Let me forward your question to @xnx. I also don't know why. Christian, can you please answer the question in this thread? This CO2 dataset is for .par format. It does not contain a parition function which somehow is conflicting with the query.

**Comment by xnx** [comment]
I think this was just a case of the Zak (17O)(12C)(18O) line list being miscategorized as a partition function. I have changed its data_type to "line list" now.
Reopen if this doesn't fix it!
