### ISSUE TITLE
`27Al-35Cl__YNAT.pf` 404s

### ISSUE THREAD

**Issue by ajwheeler** [ExoMol/exomol.com#15]
`https://exomol.com/db/AlCl/27Al-37Cl/YNAT/27Al-35Cl__YNAT.pf` is linked from the [website](https://exomol.com/data/molecules/AlCl/27Al-35Cl/YNAT/) and API, but when I try to download it, I get a 404.  

(Sorry about the issues in quick succession.)

**Comment by Trovemaster** [comment]
It should work now. I have fixed the broken link. Thanks for reporting the issue!

**Comment by ajwheeler** [comment]
Thanks!
