### ISSUE TITLE
Def file for H2_p appears missing?

### ISSUE THREAD

**Issue by gully** [ExoMol/exomol.com#19]
Hello, a link for $\mathrm{H}_2^+$ appears missing on the website:

The landing page for the resource is here: 
https://exomol.com/data/molecules/H2_p/1H2_p/ADJSAAM/ 

and the missing link is here:
https://exomol.com/db/H2_p/1H2_p/ADJSAAM/1H2_p__ADJSAAM.def

Please advise, thank you 🙏

**Comment by Trovemaster** [comment]
Thank you for letting us know. This line list page was created by mistake. We don't have an H2+ line list yet. This has now been corrected.
