### ISSUE TITLE
Wrong values in .def files (H3O+, NH3, SO2)

### ISSUE THREAD

**Issue by YuiKasagi** [ExoMol/exomol.com#20]
I would like to report some wrong values in .def files. (As of June 15, 2023.) Could you confirm and fix the following files?

|  Mol  |  Iso  |  Data sets (link to .def file)  |  column  |  wrong value (current)  |  correct value  | 
| ---- | ---- | ---- | ---- | ---- | ---- |
|  H3O+  |  1H3-16O_p  |  [eXeL](https://exomol.com/data/molecules/H3O_p/1H3-16O_p/eXeL/?export=def)  |  No. of transition files  |  101  |  100  |
|  NH3  |  14N-1H3  |  [CoYuTe](https://exomol.com/data/molecules/NH3/14N-1H3/CoYuTe/?export=def)  |  Maximum wavenumber (in cm-1)  |  23000.00  |  20000.0  |
|  SO2  |  32S-16O2  |  [ExoAmes](https://exomol.com/data/molecules/SO2/32S-16O2/ExoAmes/?export=def)  |  Maximum wavenumber (in cm-1)  |  14999.68  |  8000.0  |

They have been reported from users of radis (e.g., https://github.com/radis/radis/pull/571). And these values are also summarized in the radis code as exceptions;
https://github.com/YuiKasagi/radis/blob/3e5bf6d206c45da6dda5bd1112bade17a0d25cfb/radis/api/exomolapi.py#L131-L183
(As for CO2, CaOH, and C2H2, it seems to have already been corrected.)

Thank you in advance.

**Comment by Trovemaster** [comment]
Thanks  a lot for reporting these issues. They should be now fixed. 

Cheers, 
Sergey

**Comment by YuiKasagi** [comment]
Thank you for your prompt reply! I confirmed they were corrected, but I forgot to list up CaOH.
I am sorry to trouble you, but could you fix this too?

|  Mol  |  Iso  |  Data sets (link to .def file)  |  column  |  wrong value (current)  |  correct value  | 
| ---- | ---- | ---- | ---- | ---- | ---- |
|  CaOH  |  40Ca-16O-1H  |  [OYT6](https://www.exomol.com/db/CaOH/40Ca-16O-1H/OYT6/40Ca-16O-1H__OYT6.def)  |  Maximum wavenumber (in cm-1)  |  35000.00  |  36000.0  |

**Comment by Trovemaster** [comment]
Done.  Thanks a lot for the issues reporrted.

**Comment by YuiKasagi** [comment]
Thank you very much!
