### ISSUE TITLE
Login Issues - No Confirmation Email, Invalid Account

### ISSUE THREAD

**Issue by Stephen-Armstrong** [ExoMol/exomol.com#27]
Hi,
     Yesterday I attempted to sign-up to EXOMOL via a Chrome browser. After submitting the sign-up form I was never sent an email confirming that I signed up. Also when I attempt to login with the credentials I put, it says that my account is invalid. 

Thanks,
Stephen

**Comment by xnx** [comment]
Hello Stephen,
We should probably disable this on the public-facing website: there is no need for regular users to have an account with exomol.com: the data are all available for free without registration. If you need access for some other reason discussed with the ExoMol maintainers, please contact them and they can activate your account.
Best wishes,
Christian
