### ISSUE TITLE
OCS missing def file

### ISSUE THREAD

**Issue by cefisher** [ExoMol/exomol.com#29]
Hi, 

I wanted to use the OCS line list for some analysis, but the .def file seems to be missing? The link online goes to a 404 page. 

Thanks,

Chloe

**Comment by Trovemaster** [comment]
Thanks for reporting. It iwll be provided shortly.

**Comment by Trovemaster** [comment]
Dear Chloe,

Fixed! The .def for this line list is now available on exomol.
