### ISSUE TITLE
No. of transition files  in the def file of CH4/MM ?

### ISSUE THREAD

**Issue by HajimeKawahara** [ExoMol/exomol.com#33]
Hello, 
Thank you always for providing an excellent line list.
I regularly use the ExoMol database with [radis](https://github.com/radis/radis)/[ExoJAX](https://github.com/HajimeKawahara/exojax) [common API](https://github.com/radis/radis/blob/develop/radis/api/exomolapi.py). I am trying the new CH4 database `MM`, but it seems there is an error in [the def file](https://www.exomol.com/db/CH4/12C-1H4/MM/12C-1H4__MM.def).

I think
```
121                                                                             # No. of transition files
```
should be 
```
120                                                                             # No. of transition files
```

This variable is important because it is used in the common API to determine the name of the trans file. I would appreciate it if you could check it.

Thanks in advance.

**Comment by Trovemaster** [comment]
Dear HajimeKawahara, 
I have updated the number of files to 120. Thanks for letting us know!

Cheers, 
Sergey

**Comment by HajimeKawahara** [comment]
Dear Sergey,
Thank you for your prompt response! 

Best,
Hajime
